// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMaster.Data;

#nullable disable

namespace TaskMaster.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240719135545_DatabaseCreate")]
    partial class DatabaseCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TaskMaster.Data.Stajyer", b =>
                {
                    b.Property<int>("StajyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StajDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StajyerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StajyerUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("StajyerId");

                    b.ToTable("Stajyers");
                });

            modelBuilder.Entity("TaskMaster.Data.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskMaster.Date.TaskSave", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StajyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TaskSaveDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SaveId");

                    b.ToTable("TaskSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
