// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMaster.Data;

#nullable disable

namespace TaskMaster.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TaskMaster.Data.Engineer", b =>
                {
                    b.Property<int>("EngineerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineerUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JobDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("EngineerId");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("TaskMaster.Data.Stajyer", b =>
                {
                    b.Property<int>("StajyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StajDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StajyerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StajyerUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("StajyerId");

                    b.ToTable("Stajyers");
                });

            modelBuilder.Entity("TaskMaster.Data.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EngineerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("EngineerId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskMaster.Data.TaskSave", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StajyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TaskSaveDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SaveId");

                    b.HasIndex("StajyerId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskSaves");
                });

            modelBuilder.Entity("TaskMaster.Data.Task", b =>
                {
                    b.HasOne("TaskMaster.Data.Engineer", "Engineer")
                        .WithMany("Tasks")
                        .HasForeignKey("EngineerId");

                    b.Navigation("Engineer");
                });

            modelBuilder.Entity("TaskMaster.Data.TaskSave", b =>
                {
                    b.HasOne("TaskMaster.Data.Stajyer", "Stajyer")
                        .WithMany("TaskSaves")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskMaster.Data.Task", "Task")
                        .WithMany("TaskSaves")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stajyer");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskMaster.Data.Engineer", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskMaster.Data.Stajyer", b =>
                {
                    b.Navigation("TaskSaves");
                });

            modelBuilder.Entity("TaskMaster.Data.Task", b =>
                {
                    b.Navigation("TaskSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
